//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InvAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin  Rubik&apos;s Cube.
        /// </summary>
        internal static string IDC_APPLICATION_BTN_TITLE {
            get {
                return ResourceManager.GetString("IDC_APPLICATION_BTN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads the famous Rubik&apos;s cube game..
        /// </summary>
        internal static string IDC_APPLICATION_BTN_TOOLTIP_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDC_APPLICATION_BTN_TOOLTIP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It allows user to scramble and solve Rubik&apos;s cube. Also, it has a solver which shows the moves required to solve any scrambled Rubik&apos;s cube..
        /// </summary>
        internal static string IDC_APPLICATION_BTN_TOOLTIP_EXPANDED {
            get {
                return ResourceManager.GetString("IDC_APPLICATION_BTN_TOOLTIP_EXPANDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {07e1fdef-7a8b-4920-8501-51810a71b2bf}.
        /// </summary>
        internal static string IDC_CLIENTID {
            get {
                return ResourceManager.GetString("IDC_CLIENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IDC_EMPTY {
            get {
                return ResourceManager.GetString("IDC_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        internal static string IDC_ENV_ASSEMBLY {
            get {
                return ResourceManager.GetString("IDC_ENV_ASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubik&apos;s Cube.
        /// </summary>
        internal static string IDC_ENV_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("IDC_ENV_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RubikEnv123_.
        /// </summary>
        internal static string IDC_ENV_INTERNAL_NAME {
            get {
                return ResourceManager.GetString("IDC_ENV_INTERNAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string IDC_ENV_PART {
            get {
                return ResourceManager.GetString("IDC_ENV_PART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the next move for the solution.
        /// </summary>
        internal static string IDC_NEXT_BTN_TOOLTIP_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDC_NEXT_BTN_TOOLTIP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solves Rubik&apos;s cube and plays each move one by one on the click..
        /// </summary>
        internal static string IDC_NEXT_BTN_TOOLTIP_EXPANDED {
            get {
                return ResourceManager.GetString("IDC_NEXT_BTN_TOOLTIP_EXPANDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string IDC_NEXT_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("IDC_NEXT_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string IDC_NEXT_INTERNAL_NAME {
            get {
                return ResourceManager.GetString("IDC_NEXT_INTERNAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please launch Rubik&apos;s cube app in new empty part document..
        /// </summary>
        internal static string IDC_NOT_A_NEW_PART_DOC {
            get {
                return ResourceManager.GetString("IDC_NOT_A_NEW_PART_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows all the moves in the solution .
        /// </summary>
        internal static string IDC_PLAY_BTN_TOOLTIP_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDC_PLAY_BTN_TOOLTIP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solves Rubik&apos;s cube and plays all the moves like animation. User can see each step one by one by clicking on Next..
        /// </summary>
        internal static string IDC_PLAY_BTN_TOOLTIP_EXPANDED {
            get {
                return ResourceManager.GetString("IDC_PLAY_BTN_TOOLTIP_EXPANDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string IDC_PLAY_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("IDC_PLAY_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string IDC_PLAY_INTERNAL_NAME {
            get {
                return ResourceManager.GetString("IDC_PLAY_INTERNAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrambles the Rubik&apos;s cube randomly..
        /// </summary>
        internal static string IDC_SCRAMBLE_BTN_TOOLTIP_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDC_SCRAMBLE_BTN_TOOLTIP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to scramble Rubik&apos;s cube. User can scramble the Rubik&apos;s cube any number of times..
        /// </summary>
        internal static string IDC_SCRAMBLE_BTN_TOOLTIP_EXPANDED {
            get {
                return ResourceManager.GetString("IDC_SCRAMBLE_BTN_TOOLTIP_EXPANDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble.
        /// </summary>
        internal static string IDC_SCRAMBLE_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("IDC_SCRAMBLE_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble.
        /// </summary>
        internal static string IDC_SCRAMBLE_INTERNAL_NAME {
            get {
                return ResourceManager.GetString("IDC_SCRAMBLE_INTERNAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to play with Rubik&apos;s cube manually..
        /// </summary>
        internal static string IDC_SOLVE_BTN_TOOLTIP_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDC_SOLVE_BTN_TOOLTIP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can rotate any face of the Rubik&apos;s cube by dragging the face in the desired direction like real world Rubik&apos;s cube..
        /// </summary>
        internal static string IDC_SOLVE_BTN_TOOLTIP_EXPANDED {
            get {
                return ResourceManager.GetString("IDC_SOLVE_BTN_TOOLTIP_EXPANDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve.
        /// </summary>
        internal static string IDC_SOLVE_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("IDC_SOLVE_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve.
        /// </summary>
        internal static string IDC_SOLVE_INTERNAL_NAME {
            get {
                return ResourceManager.GetString("IDC_SOLVE_INTERNAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubik&apos;s Cube.
        /// </summary>
        internal static string IDC_TAB_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("IDC_TAB_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubik&apos;sCube_internal.
        /// </summary>
        internal static string IDC_TAB_INTERNAL_NAME {
            get {
                return ResourceManager.GetString("IDC_TAB_INTERNAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_TabEnvironments.
        /// </summary>
        internal static string IDC_TARGET_TAB_NAME {
            get {
                return ResourceManager.GetString("IDC_TARGET_TAB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Next_16 {
            get {
                object obj = ResourceManager.GetObject("Next_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Next_32 {
            get {
                object obj = ResourceManager.GetObject("Next_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Play_16 {
            get {
                object obj = ResourceManager.GetObject("Play_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Play_32 {
            get {
                object obj = ResourceManager.GetObject("Play_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Rubiks_Cube_16 {
            get {
                object obj = ResourceManager.GetObject("Rubiks_Cube_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Rubiks_Cube_32 {
            get {
                object obj = ResourceManager.GetObject("Rubiks_Cube_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Scramble_16 {
            get {
                object obj = ResourceManager.GetObject("Scramble_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Scramble_32 {
            get {
                object obj = ResourceManager.GetObject("Scramble_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Solve_16 {
            get {
                object obj = ResourceManager.GetObject("Solve_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Solve_32 {
            get {
                object obj = ResourceManager.GetObject("Solve_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
